<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-678</name>
   <tag></tag>
   <elementGuidId>b7039179-4b44-4538-9d9b-50e600e8353c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-678']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-678</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>615c2245-33f1-44dc-bcdd-b2f418558733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-678</value>
      <webElementGuid>2b9a7ae0-7124-489f-9a1b-e3ac26da00ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Postal / Zip Code</value>
      <webElementGuid>b53785c4-5683-47d5-8edb-f287c75b9a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13bd17b5-1406-44b6-ae84-61d4ac545ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-678&quot;)</value>
      <webElementGuid>20c94f21-e96b-4b27-8d75-4712e3202db2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-678']</value>
      <webElementGuid>64b2f48a-393d-440c-b46b-f2854cdc176c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div[2]/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>3208d275-8eb5-4297-be42-de1b70e4eb6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>0f2c6f66-4762-46cf-b645-cf3eea5795a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-678' and @placeholder = 'Enter Postal / Zip Code' and @type = 'text']</value>
      <webElementGuid>61baa983-c3bc-4be3-a1ec-f8956941ff0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
