<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-621</name>
   <tag></tag>
   <elementGuidId>5d989c36-7f40-4967-bf60-39c407b95876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-621']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-621</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e83e959b-3769-4ef9-bf18-3fcbacb167e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-621</value>
      <webElementGuid>a201bafe-b44c-4d70-8617-48b04f2ba283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Subheading</value>
      <webElementGuid>8ce625c2-96ab-4bf3-9aca-1559ae24160b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7629d2b-944b-4300-b7a4-17d79d5ffd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-621&quot;)</value>
      <webElementGuid>9783efe5-d6a3-427a-b402-c16aacb98d8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-621']</value>
      <webElementGuid>1b1bb333-af5a-4eec-9532-018c4aef1c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div/div/div/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>d3951169-66cd-4fa5-a98e-75f8eac99da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>134c0710-6cd7-4f36-9de1-61a54472a0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-621' and @placeholder = 'Enter Subheading' and @type = 'text']</value>
      <webElementGuid>3966feca-ad47-4370-ad7f-7af9efb71a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
