<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-727</name>
   <tag></tag>
   <elementGuidId>1d0a690a-203f-4cd1-bf73-6e51e92d5621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-727']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-727</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eea86b3c-ba56-4ef4-9a49-8f3a474857b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-727</value>
      <webElementGuid>aa702c78-35b5-454b-bf1c-7ade8e153cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Quantity</value>
      <webElementGuid>b39c5cc0-9803-4ca9-ba7a-7ded989312a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e506f6df-b9fe-44c2-bc8f-120e31db7639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-727&quot;)</value>
      <webElementGuid>62e27671-ee75-4c7a-8c9c-6f5649517d8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-727']</value>
      <webElementGuid>ebba479c-05b5-4e01-8212-e05f870b9581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[4]/div/div/table/tbody/tr/td[3]/div/div/div/div/input</value>
      <webElementGuid>ba06a9c3-0bf7-46e8-a267-a34aa8ea2c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/div/input</value>
      <webElementGuid>46293d0a-925b-43a0-876e-994f4c376388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-727' and @placeholder = 'Enter Quantity' and @type = 'number']</value>
      <webElementGuid>75f44081-5d99-4ea2-903d-474e4fa13472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
