<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-721</name>
   <tag></tag>
   <elementGuidId>19495782-edea-4889-9cda-e867ac2ec58a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-721']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-721</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ee65e9b-4d10-4127-8b5b-f275d8028ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-721</value>
      <webElementGuid>d3fb6520-ba9b-4586-9c3e-32beefa08ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Item Name</value>
      <webElementGuid>658281d4-1d2e-4603-b2ad-65a966b18aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88af0804-2cee-407d-a6a5-6f1e5980f99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-721&quot;)</value>
      <webElementGuid>a0f4cbb9-3ae0-4890-bc05-aaebe603747c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-721']</value>
      <webElementGuid>1e34e90b-bad1-4674-9fac-cafc8a3c504d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[4]/div/div/table/tbody/tr/td/div/div/div/div/input</value>
      <webElementGuid>c6fa30cb-949c-4ed3-b5aa-29cec0231234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/input</value>
      <webElementGuid>5ba966da-0bac-47d7-a5bc-4666a90ca619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-721' and @placeholder = 'Enter Item Name' and @type = 'text']</value>
      <webElementGuid>a94e5c25-e787-4610-a577-15d44e7be9c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
