<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_MAKS. Ukuran file  10MB</name>
   <tag></tag>
   <elementGuidId>2a652233-02dc-4731-8321-fe52323e2a6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[3]/div/div/div/div[2]/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.text-center.mb-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>eebd1f26-e1d6-424f-8cf4-c290c20e52c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center mb-5</value>
      <webElementGuid>392f528f-df00-42c0-8e4b-cd713b691107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MAKS. Ukuran file : 10MB</value>
      <webElementGuid>a9065c99-4a93-4d26-a9fd-6db77dd7c0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-dialog__content v-dialog__content--active&quot;]/div[@class=&quot;v-dialog v-dialog--active&quot;]/div[@class=&quot;v-card v-sheet theme--light rounded-lg&quot;]/div[@class=&quot;container px-0 container--fluid&quot;]/div[@class=&quot;px-15 py-10&quot;]/div[@class=&quot;container import-file-dropzone rounded-xl&quot;]/p[@class=&quot;text-center mb-5&quot;]</value>
      <webElementGuid>79134b6b-e9b6-420e-a239-f36360810cb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div[2]/div/p[2]</value>
      <webElementGuid>d6092175-59c6-478c-9680-33a348fd85f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impor'])[1]/following::p[3]</value>
      <webElementGuid>f5a4466a-3eb5-4714-9e2a-3f85317910ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ekspor'])[1]/following::p[3]</value>
      <webElementGuid>17e92a78-8a4c-4af0-b302-58069e60a21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MAKS. Ukuran file : 10MB']/parent::*</value>
      <webElementGuid>745cf431-897d-4c3a-a467-ca7ec31c420f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/p[2]</value>
      <webElementGuid>2f2f4590-0f83-4608-bd74-c3c8cb987e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'MAKS. Ukuran file : 10MB' or . = 'MAKS. Ukuran file : 10MB')]</value>
      <webElementGuid>ec43dbd6-5370-4b5b-be90-b31e7ca9a78c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
