<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Action_v-icon notranslate mdi mdi-checkbo_247d5b</name>
   <tag></tag>
   <elementGuidId>052ea730-a519-49c7-94e3-f4d9e6f01052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div/div[2]/div[3]/div/table/tbody/tr/td/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.text-start > div.v-data-table__checkbox.v-simple-checkbox > div.v-input--selection-controls__input > i.v-icon.notranslate.mdi.mdi-checkbox-blank-outline.theme--light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>73065e3e-2250-4b14-954e-1ab64eeb191d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c24e406-7f77-4dc0-8b77-9d0999a923e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate mdi mdi-checkbox-blank-outline theme--light</value>
      <webElementGuid>06998aed-4b4e-4b6b-af47-a9ea83e7bda8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container container--fluid main-content-bg fill-height align-start pa-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;container pa-0 mt-3&quot;]/div[@class=&quot;v-data-table elevation-2 data-table-wrapper theme--light&quot;]/div[@class=&quot;v-data-table__wrapper&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;text-start&quot;]/div[@class=&quot;v-data-table__checkbox v-simple-checkbox&quot;]/div[@class=&quot;v-input--selection-controls__input&quot;]/i[@class=&quot;v-icon notranslate mdi mdi-checkbox-blank-outline theme--light&quot;]</value>
      <webElementGuid>21409064-e690-4e7b-8a5d-81aee122e9bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div[2]/div[3]/div/table/tbody/tr/td/div/div/i</value>
      <webElementGuid>64494984-7be2-42d0-b958-4262cd1029da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/i</value>
      <webElementGuid>efa3ca38-6f53-4980-b6ec-a106c6686491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
