<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lupa Password_input-17</name>
   <tag></tag>
   <elementGuidId>5c3ca71a-ff1e-4243-96dd-9e7f9ed7ac62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-17']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20b800d8-45c5-4166-a4e1-aca99bf2eb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-17</value>
      <webElementGuid>60fea2b7-ca10-4988-a7f1-bcf677379448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email</value>
      <webElementGuid>95491bbe-27c5-4e13-8341-13ccb59df6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1f722e1-8423-46fa-968a-a1c4b0719169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-17&quot;)</value>
      <webElementGuid>f570b4bb-2e27-4c7b-ad33-26664f0bf907</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-17']</value>
      <webElementGuid>ede1135f-e906-456b-864d-910550c4aa36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>2a3aa559-dec7-43fd-9f19-7357c4a0a727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d4db553a-44a7-4218-bd15-fc21b96b071f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-17' and @placeholder = 'Masukkan Email' and @type = 'text']</value>
      <webElementGuid>182a62ea-ece6-4c9c-bafb-a9ac41c73cc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
