<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-82</name>
   <tag></tag>
   <elementGuidId>2ffbf35e-5482-4d37-94b9-5860700c5535</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-82</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-82']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c1d5e19-042f-4e09-a40b-5019c2c98e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-82</value>
      <webElementGuid>650f94aa-90fc-41c5-8e21-226b6d6563bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Invoice</value>
      <webElementGuid>7aae8103-97c3-406c-8d43-c12f7b2b0507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71fd4711-d7dc-4bcb-9900-ebdf4fbfc3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-82&quot;)</value>
      <webElementGuid>fbfef96c-63af-4a8b-a586-6624babe5117</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-82']</value>
      <webElementGuid>8ec2487c-3c86-46a5-a47b-ad1e110d66d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>6c5b247e-6d18-49d7-a029-5f232ef95476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c31e4056-35f9-4978-88aa-c2dca4a02282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-82' and @placeholder = 'Search Invoice' and @type = 'text']</value>
      <webElementGuid>53a5d409-c16b-4450-90aa-65d903b46f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
