<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-393</name>
   <tag></tag>
   <elementGuidId>d82fcced-2cf9-4ab5-b4fd-05b7901798b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-393']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-393</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffe5bc44-554b-41f6-9a3b-61ca664bb38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-393</value>
      <webElementGuid>50518ca4-ff28-4b61-999a-985b7ffec2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Postal / Zip Code</value>
      <webElementGuid>d0b8f6bf-d74c-46d7-a09a-767648fcb310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e7f5ec3-eb4d-466d-9552-bce9501bee55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-393&quot;)</value>
      <webElementGuid>02864f19-0a78-4fc7-b25c-1f005635e775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-393']</value>
      <webElementGuid>f058b945-4a7e-4e2e-92e2-5bd0837bc0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div[2]/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>e9147b99-2ce8-422d-a7ef-f08b986b0aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>3b8c5de9-1c1c-4ac7-a88a-a0bc674929ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-393' and @placeholder = 'Enter Postal / Zip Code' and @type = 'text']</value>
      <webElementGuid>c6092fa9-ad60-4942-bed9-df1196ef9c0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
