<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lupa Password_input-163</name>
   <tag></tag>
   <elementGuidId>479277dc-469e-4b5b-aea1-6afab1df9c6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-163</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-163']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5aa01d36-d35a-4319-948a-41610ae5e7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-163</value>
      <webElementGuid>6737260e-a022-47d7-bf79-565c7535a8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email</value>
      <webElementGuid>a9a6de33-f6cb-4a35-a231-0f4cfbc9d0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b2768dc-de52-4ed8-a02d-d29d6d828e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-163&quot;)</value>
      <webElementGuid>246aea9f-99ca-430b-bec5-7d29000f06a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-163']</value>
      <webElementGuid>ea86773c-aad1-4a88-8a5e-38faf4d745a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>d936bba6-3653-4a03-8f76-eb330c093284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1cf1223c-a97d-4e07-a9c1-9e0aa4f6a211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-163' and @placeholder = 'Masukkan Email' and @type = 'text']</value>
      <webElementGuid>c0cae156-25c1-46d2-a433-54ffa993c3b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
