<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_input-446</name>
   <tag></tag>
   <elementGuidId>9b2ad5d5-f5d7-4fb7-8d66-6271dc1e9631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-446']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-446</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dc088d8-63cf-4697-8944-a60e6d065761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-446</value>
      <webElementGuid>44e477d4-9bd7-47cd-9ebb-78cd9f2250e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Price</value>
      <webElementGuid>5d5ee775-fa8c-41a0-8ed8-1cbdf9693865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41436e36-588a-4c49-ab61-7728409825e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>c1474294-2129-4ad1-b083-ef43552f1bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-446&quot;)</value>
      <webElementGuid>52b0f7de-d249-474d-8022-d2cab168931e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-446']</value>
      <webElementGuid>6fbf4451-2d6b-404a-86b4-1588c2eb0385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[4]/div/div/table/tbody/tr/td[4]/div/div/div/div/input</value>
      <webElementGuid>5bc6a88b-dbef-4729-94a0-b6bd9a0602fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div/div/div/input</value>
      <webElementGuid>0f3a5ab1-e1b3-4262-9693-f76dcdea36d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-446' and @placeholder = 'Enter Price' and @type = 'text']</value>
      <webElementGuid>f3dc6595-aebd-4579-b087-8141b4f398ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
