<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Syarat  Ketentuan, Kebijakan Privasi _d9a892</name>
   <tag></tag>
   <elementGuidId>f558be5a-8178-4df3-917f-5b4e3afc826e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-169</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-169']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a4da36e-3848-404b-9fc4-7b172321f8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-169</value>
      <webElementGuid>c3d44f3d-9840-48fc-9219-b2687be36949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan email</value>
      <webElementGuid>90d8ffc3-86e1-4de7-a4bb-2403223d3aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f73d8fc-0625-45b7-b942-31ab9cb331cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-169&quot;)</value>
      <webElementGuid>b4c2bab1-429a-4b43-abcb-dff21640c6db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-169']</value>
      <webElementGuid>946acfdc-2639-4d4e-bf27-3772e1848d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>a9097030-d317-486f-be64-b2d6fc128fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>6ec3efed-2146-4b64-b216-99e02f50a363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-169' and @placeholder = 'Masukkan email' and @type = 'text']</value>
      <webElementGuid>686c7279-c208-4343-a6ba-de16eda72b01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
