<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Action_v-icon notranslate mdi mdi-checkbo_247d5b</name>
   <tag></tag>
   <elementGuidId>957442ee-50cf-46da-8fba-b563abedadd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div/div[2]/div[3]/div/table/tbody/tr/td/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.text-start > div.v-data-table__checkbox.v-simple-checkbox > div.v-input--selection-controls__input > i.v-icon.notranslate.mdi.mdi-checkbox-blank-outline.theme--light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a3f05e73-6666-45a3-8411-60b47b058b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8f227939-418b-4f85-b720-be8ebc9a78b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate mdi mdi-checkbox-blank-outline theme--light</value>
      <webElementGuid>02df0a2e-28ed-4706-aec3-f9dea7c506b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container container--fluid main-content-bg fill-height align-start pa-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;container pa-0 mt-3&quot;]/div[@class=&quot;v-data-table elevation-2 data-table-wrapper theme--light&quot;]/div[@class=&quot;v-data-table__wrapper&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;text-start&quot;]/div[@class=&quot;v-data-table__checkbox v-simple-checkbox&quot;]/div[@class=&quot;v-input--selection-controls__input&quot;]/i[@class=&quot;v-icon notranslate mdi mdi-checkbox-blank-outline theme--light&quot;]</value>
      <webElementGuid>462ac940-1adb-4b91-8bba-25a7f04528fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div[2]/div[3]/div/table/tbody/tr/td/div/div/i</value>
      <webElementGuid>ad24c6af-8213-4f62-a91d-40965bbbf49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/i</value>
      <webElementGuid>c937cfcc-b0ff-4520-babf-7bd95358f533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
