<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-187</name>
   <tag></tag>
   <elementGuidId>84d8fef2-3723-4f44-86ae-65e09e0e9fe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-187']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-187</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>909d09c2-c0ba-4aae-ac5a-fea2c9371804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-187</value>
      <webElementGuid>ddfe3708-410e-4453-ba10-fa4844377f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Client</value>
      <webElementGuid>067dc81d-366c-4c58-8ae0-7aaf1a5037f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>03e8563a-34cb-4d6f-bc42-d769fc7f16b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-187&quot;)</value>
      <webElementGuid>c6f12d3d-7b6c-47fc-a0e2-7227c5b7ac53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-187']</value>
      <webElementGuid>a8e96792-f25b-41ee-ac1a-28b79e07c36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>3b28988d-3435-495d-a6fb-047ef7852409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f7ab11a3-7ca3-4ace-b609-dad3cbe7dc24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-187' and @placeholder = 'Search Client' and @type = 'text']</value>
      <webElementGuid>495d60f8-4f88-452f-8274-429a4be22962</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
