<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-381</name>
   <tag></tag>
   <elementGuidId>6ab59e29-b8de-4bbe-9742-f0b6805e409e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-381']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-381</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5f11c90-5422-44b2-90ed-6e64fec26e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-381</value>
      <webElementGuid>e1df8f1d-faf0-4e25-bc6f-cb0fcd561576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Districts</value>
      <webElementGuid>0be6ee05-fb10-4a03-bb8c-6d4bdc22263d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>824409b4-bf7f-4d32-b1ac-b4bc4c1396d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e6ee6366-f6a1-4dc2-8a92-cb961d58323e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-381&quot;)</value>
      <webElementGuid>911a130c-5396-475e-b8dd-44daa5d8aae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-381']</value>
      <webElementGuid>5b8cd4c8-86c9-46d0-8268-1193f26d579b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div[2]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>7d048748-8d04-4001-aaca-052669ca8c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>aefd8912-2f3d-4364-92fe-0b2acd2523e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-381' and @placeholder = 'Enter Districts' and @type = 'text']</value>
      <webElementGuid>451494d7-3187-476d-91c2-b1e7e35fb1b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
