<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-236</name>
   <tag></tag>
   <elementGuidId>8eade8e5-13d6-44d7-9b8a-ed6f86be194b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-236</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-236']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6c1de9f-06b0-47ca-ae65-eea04ce4ac74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-236</value>
      <webElementGuid>d109b742-92f9-4f91-80e9-61c1b89de9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Phone</value>
      <webElementGuid>1092af1d-8f61-4a10-8c37-88543f15d494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>37a35b17-073a-4859-9bca-d0e679e6e09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-236&quot;)</value>
      <webElementGuid>d5a1787d-0412-4310-89a0-8fc36a5db294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-236']</value>
      <webElementGuid>9df90b0b-d102-403f-95ff-0b250fc25953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>2146775d-d13b-4fb9-a058-48d10343369c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>04f91e6c-5896-465e-b59c-bd5fa8578d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-236' and @placeholder = 'Enter Phone' and @type = 'text']</value>
      <webElementGuid>91bc0048-5a71-4e6d-ac58-837a74a451fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
