<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-228</name>
   <tag></tag>
   <elementGuidId>b46f794f-ef1f-43b7-86aa-e1cd669e00bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-228</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-228']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6782272a-d672-46d9-bf49-6fc5f57a7a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-228</value>
      <webElementGuid>85826c70-294a-434a-b08f-d1b5ed6c9f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Last Name</value>
      <webElementGuid>fa6235d5-90ca-477c-9b9f-1462f35039c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20394831-1846-4232-a418-8b36d6741b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-228&quot;)</value>
      <webElementGuid>2b1ba295-16c6-4ff6-af7a-5e607784d652</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-228']</value>
      <webElementGuid>2159e096-a797-4104-ab47-87b40db47e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>f39196b3-3cb3-4bee-845e-69ee94ea4b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>81e546e7-35f8-4262-b0aa-e15d7c168f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-228' and @placeholder = 'Enter Last Name' and @type = 'text']</value>
      <webElementGuid>e42165c5-e6f1-4685-950d-adf716817e33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
