<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-232</name>
   <tag></tag>
   <elementGuidId>74cbcb0a-1828-4b65-9402-3387b42e73a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-232</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-232']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>608e7f99-4d85-45f9-9c61-cc0584eb94ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-232</value>
      <webElementGuid>a4994ae1-de7c-44c7-be1c-598f0e815cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Email</value>
      <webElementGuid>5f21c97a-39e1-41c8-b2d8-4d98991ad0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16ba1dfa-93a3-4776-a1e1-f3d5c41ed077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-232&quot;)</value>
      <webElementGuid>a57c98eb-284f-4d57-8825-acc085a43898</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-232']</value>
      <webElementGuid>81d76b7b-0e8d-452f-9455-9b1619bfa02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>cd915c6a-ce63-425e-8daf-14eaaf932ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>3c8b8215-e30d-45d4-8882-4e685d59f53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-232' and @placeholder = 'Enter Email' and @type = 'text']</value>
      <webElementGuid>f26fc9bc-6685-4ff0-8890-d1b51607cccc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
