<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Syarat  Ketentuan, Kebijakan Privasi _4f0e13</name>
   <tag></tag>
   <elementGuidId>b1856d29-0f89-47b4-96d7-f18e8a8714d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-165</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-165']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf4c6a9f-73c3-4265-bf3e-bd9db7e01754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-165</value>
      <webElementGuid>414c8de5-6829-4e96-93f2-c17b42e89d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama</value>
      <webElementGuid>bb084065-b5c5-41d0-aa31-2ee837753d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54a3c809-9b74-4800-bcc4-8a3ad35a0edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-165&quot;)</value>
      <webElementGuid>0c3b4cdc-eded-4938-94ca-2ea167d4456f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-165']</value>
      <webElementGuid>9d38acaa-51b8-4c53-a282-8739b1d20813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>9b513465-39b1-434f-9776-1156c810efa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b4a2dfae-9075-4b5e-9e6f-3085e60a32ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-165' and @placeholder = 'Masukkan nama' and @type = 'text']</value>
      <webElementGuid>80fd8ffd-fa20-4907-9ac3-8770e005f49e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
