<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukkan password minimal 8 karakter__e7b54d</name>
   <tag></tag>
   <elementGuidId>bbe60447-4dcc-4bec-ab35-e6af2fce1b90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-173</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-173']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d006f891-2221-4dd6-88d6-2fa81a8c931b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-173</value>
      <webElementGuid>82f98924-b06f-4b17-93bf-1414769a33c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan password</value>
      <webElementGuid>c89cc3e6-d6ec-4ecc-ae73-bf9ad576d0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a0d86c3f-d689-41b2-8787-a4caf9a3a477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-173&quot;)</value>
      <webElementGuid>05e081cd-f279-4631-9731-73f00ec47b30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-173']</value>
      <webElementGuid>e3cff6ef-1da1-4a1f-a1d1-fa66a5b00394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[3]/div/div/div/input</value>
      <webElementGuid>c3c0175b-f48e-4848-8076-a904b77412fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>c0a4e27d-05a4-48d4-ad0d-e2b4bfa3f585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-173' and @placeholder = 'Masukkan password' and @type = 'password']</value>
      <webElementGuid>c11b89c2-79f1-493f-a7e9-7383af06812d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
