<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Konfirmasi Password tidak sesuai_input-178</name>
   <tag></tag>
   <elementGuidId>53af9130-af49-4ff0-8f34-a629815f7398</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-178</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-178']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6985a38-d514-4326-8527-32f1bd11e887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-178</value>
      <webElementGuid>53b6b951-4ce2-4c82-8c3d-04c63c617df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan password</value>
      <webElementGuid>414229c5-b163-40ee-bd8d-a3d06f9c1093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>81920477-f56b-49a5-b340-d559cdc4573c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-178&quot;)</value>
      <webElementGuid>5236a602-5a07-41ca-8d5f-2dd24d62e752</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-178']</value>
      <webElementGuid>0f0ebc99-6348-4512-ad8d-e133bad28b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[4]/div/div/div/input</value>
      <webElementGuid>d538f27c-3c3d-4e91-b21b-ef89054b190e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>b768b193-c0ab-4f54-97e0-1add1fc8f4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-178' and @placeholder = 'Masukkan password' and @type = 'password']</value>
      <webElementGuid>b47fc58a-4324-4fb5-8d1c-56292003e654</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
