<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama tidak boleh kosong_input-19</name>
   <tag></tag>
   <elementGuidId>6ccdd888-656f-455d-99c5-5611ab9d93b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-19']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-19</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8985e7c-7a4d-4f9b-9d99-9bc5fb1226b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-19</value>
      <webElementGuid>a6a870d7-3130-42ca-b829-66a76a54c223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama</value>
      <webElementGuid>7e44561d-1a5a-4c03-8489-eef9c8ad148e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>67c2444a-b884-4d60-ad8e-b782b7dbd500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-19&quot;)</value>
      <webElementGuid>1e8c00ea-e778-4490-856f-5a86e6d09cc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-19']</value>
      <webElementGuid>4c7a4126-2c0d-4b67-b617-a0cd149b1077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>294bd30e-5e64-4f34-97ac-e1baee680574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>41c5c022-e078-4f24-9cbb-1f001b89f10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-19' and @placeholder = 'Masukkan nama' and @type = 'text']</value>
      <webElementGuid>52e5466f-d18c-47ee-a5e2-d6e85a42cc8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
