<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-332</name>
   <tag></tag>
   <elementGuidId>65c7bec0-745a-4603-8da7-c5305f00b05f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-332']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-332</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bb285b7-4bc4-4ec6-aae4-d42ded2aec1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-332</value>
      <webElementGuid>00bab74b-5a27-46eb-a442-598c25693de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Title</value>
      <webElementGuid>e49ffde3-e2cf-42cf-91bc-e0dc5918050d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3161f5b-ffc6-4aa5-befd-8d1f6203313a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-332&quot;)</value>
      <webElementGuid>3037204f-cf1a-4cf9-b1bc-5235f4b1c1ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-332']</value>
      <webElementGuid>a92f7d80-2b52-423b-b8bd-d29533c49dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>131712c6-2c05-4292-a356-7e1de945bc59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>171156d4-e766-44da-8a1c-66417e456330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-332' and @placeholder = 'Enter Title' and @type = 'text']</value>
      <webElementGuid>54ded5d1-275a-4464-8f8e-44fdc886a885</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
