<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-436</name>
   <tag></tag>
   <elementGuidId>ab451e49-c7da-4fbb-a752-a3be888930d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-436']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-436</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f81a1dd-aafc-4d74-b0e7-41456dcae6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-436</value>
      <webElementGuid>5fb9fb9b-6a17-48f9-bdbc-d7c47818cf4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Item Name</value>
      <webElementGuid>1a3dab22-0661-4493-a830-05bb96673d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>906423df-3ee3-4e61-8f58-19523e41c49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-436&quot;)</value>
      <webElementGuid>c2067c20-1e3e-4afe-b2d7-6e39573251ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-436']</value>
      <webElementGuid>cb6f326a-af4a-41d3-bf0c-447c54e86cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[4]/div/div/table/tbody/tr/td/div/div/div/div/input</value>
      <webElementGuid>2dea9420-01df-41bb-a107-18a5dd9a00f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/input</value>
      <webElementGuid>8da1b76c-48b9-45ec-ae6a-a1e20a6dbcb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-436' and @placeholder = 'Enter Item Name' and @type = 'text']</value>
      <webElementGuid>ee4fb981-4c0d-4ef6-be3e-8ea05286edd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
