<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password tidak boleh kosong_input-21</name>
   <tag></tag>
   <elementGuidId>0924bde0-6420-42ab-941b-c60db6bc70a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a1f508e-3a77-4104-b843-430d4a0f245c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-21</value>
      <webElementGuid>f0021052-a833-47f4-9358-06bf9c553c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Password</value>
      <webElementGuid>3fa81fd0-1c5a-494b-97af-4a3bae0a9449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>dcd17989-4a61-419e-8130-a9280a1e0486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-21&quot;)</value>
      <webElementGuid>a52986de-d1f6-4059-b074-77336c8eec05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-21']</value>
      <webElementGuid>cbbba6fc-f0b3-404d-8edb-5a26d8c6c555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[2]/div/div/div[2]/input</value>
      <webElementGuid>8a532481-6b27-42de-b05f-4488adc08ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>7d72bf70-183c-4bf3-8b3b-5c17e7f3ff4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-21' and @placeholder = 'Masukkan Password' and @type = 'password']</value>
      <webElementGuid>5beffa0c-db6e-4bf3-a9fe-bbf9f549c03a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
