<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-236</name>
   <tag></tag>
   <elementGuidId>be68e035-0b3f-4e13-b2c2-7f199b9c9982</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-236</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-236']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b23dd7bd-ba0b-4052-bd4c-5e4bc28e3e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-236</value>
      <webElementGuid>98534e76-5f3f-4133-9e33-1bb1fc5f42da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Phone</value>
      <webElementGuid>56d996bf-8772-4ecd-a289-84ba7971c443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7795db39-6f35-4d64-9fed-b7ebf1634896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-236&quot;)</value>
      <webElementGuid>3134eee2-18bb-4f0d-aa42-433207622a2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-236']</value>
      <webElementGuid>1a426d58-4da9-4137-b7a9-3fbd0a7bccd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>3e1e6f81-de8e-45be-abf7-d8c8d72629c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>b6e7e0e4-aa00-4712-adf0-c68929360abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-236' and @placeholder = 'Enter Phone' and @type = 'text']</value>
      <webElementGuid>fcd06151-7ef9-4dd1-af9c-0f1c27bfbdf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
