<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-228</name>
   <tag></tag>
   <elementGuidId>baf8f911-b5b2-47c5-801b-c910e7356160</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-228</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-228']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bccb409c-36f8-4e6b-9c43-15b7e06adea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-228</value>
      <webElementGuid>1614bb43-9b3e-48b1-9e4f-f701fba0a005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Last Name</value>
      <webElementGuid>5ff870cd-b562-4e1b-b806-a4507803f92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2663ec9f-7eaf-4bcc-9afe-45033a2a1db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-228&quot;)</value>
      <webElementGuid>f425b43d-48b4-46c8-aca9-35357b337aef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-228']</value>
      <webElementGuid>fd4815c7-68bf-41f0-974f-e812f9d488a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>cc61de74-7e91-41c0-8dc5-aaa406c951dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>282d65fa-b926-4088-ad58-fb81618eb540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-228' and @placeholder = 'Enter Last Name' and @type = 'text']</value>
      <webElementGuid>1d431977-8279-4f81-bff3-51c4ccb25b15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
