<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_13</name>
   <tag></tag>
   <elementGuidId>c6329b74-6a9a-466e-8381-6c9a6874eed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[23]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54c26f82-4aaf-443d-923e-669fe4cf387c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00ee9d90-8a64-4d88-bbb8-26a6aa7cb14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--text v-btn--rounded theme--light</value>
      <webElementGuid>2531150d-9048-42b0-be65-da602db3ba34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>5c2bb7d7-33f0-42d4-b629-1d313caf359c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-menu__content theme--light menuable__content__active&quot;]/div[@class=&quot;pa-3 v-card v-sheet theme--light&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-center&quot;]/div[@class=&quot;pa-0 col col-auto&quot;]/div[@class=&quot;v-picker v-card v-picker--date theme--light&quot;]/div[@class=&quot;v-picker__body v-picker__body--no-title theme--light&quot;]/div[1]/div[@class=&quot;v-date-picker-table v-date-picker-table--date theme--light&quot;]/table[1]/tbody[1]/tr[3]/td[4]/button[@class=&quot;v-btn v-btn--text v-btn--rounded theme--light&quot;]</value>
      <webElementGuid>0db28a29-9ea8-4613-926d-d57339c907e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[23]</value>
      <webElementGuid>e5a67da9-843d-4bce-b15e-04b664ce61e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div/div/div/div/div/div[2]/table/tbody/tr[3]/td[4]/button</value>
      <webElementGuid>420fee55-715c-4d09-853e-852b67b1c14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::button[13]</value>
      <webElementGuid>186eed4b-0ffd-474b-a3d2-0566b3ddb9e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::button[13]</value>
      <webElementGuid>fe1f3cfe-280b-4622-9e74-571985bafe01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CANCEL'])[1]/preceding::button[19]</value>
      <webElementGuid>aeb3b49b-8384-4491-864d-b3b701cd26e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVE'])[1]/preceding::button[20]</value>
      <webElementGuid>f2158867-6726-4f1c-badc-a561ca893929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/button</value>
      <webElementGuid>cb147106-313a-4123-9064-5b19c33f6c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '13' or . = '13')]</value>
      <webElementGuid>b830b71d-12c6-4456-b67d-d8836d7bb6a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
