<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-420</name>
   <tag></tag>
   <elementGuidId>d9b2bc55-09be-4e3a-ad53-7d375770e154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-420']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-420</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df13b091-7862-4e0b-8144-ea82211778d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-420</value>
      <webElementGuid>e31e060b-5072-4ff2-8e19-884305086731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Invoice Number</value>
      <webElementGuid>3119af15-58bd-4f1e-8cfc-4fc8a267f2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d441820-eb86-47de-a25c-11ed423c3206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-420&quot;)</value>
      <webElementGuid>ac116514-7be2-4e46-b004-2c3e05797661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-420']</value>
      <webElementGuid>dc984757-60c5-46a4-a0fa-7d79edb0d02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[3]/div/div/div[3]/div/div/div/div/input</value>
      <webElementGuid>8c65b687-5817-470d-87a6-cd2ffb209427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>cf106c48-7454-4d46-86ef-5a5971ca193d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-420' and @placeholder = 'Enter Invoice Number' and @type = 'text']</value>
      <webElementGuid>ecdc0a44-69e4-486e-ba71-3f0dcb012689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
