<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-442</name>
   <tag></tag>
   <elementGuidId>724a8a67-2a1d-484b-a2fe-4c9115de05d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-442']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-442</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b4dec7c-3e86-46be-ac9a-cde0ab6a8eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-442</value>
      <webElementGuid>5a26bf59-69ad-4bbe-ace3-0c552c99c2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Quantity</value>
      <webElementGuid>9231d1c5-bd6f-4ef7-ae31-4a13e93c907e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>37d0f140-8c45-495c-9ffd-9caf1a2bb840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-442&quot;)</value>
      <webElementGuid>bdc231ad-f6b1-4e4b-aa5c-1975863220f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-442']</value>
      <webElementGuid>96701996-5893-45b0-9e6d-bd242bb0218f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[4]/div/div/table/tbody/tr/td[3]/div/div/div/div/input</value>
      <webElementGuid>2b9a6717-3375-4ede-9af4-02771cbad3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/div/input</value>
      <webElementGuid>afe41441-5861-4d61-9699-778b8fdb2099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-442' and @placeholder = 'Enter Quantity' and @type = 'number']</value>
      <webElementGuid>f367114a-bdbc-4e1a-9e69-16bc4927e865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
