<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__input-439</name>
   <tag></tag>
   <elementGuidId>5afcdd01-7d8b-46e5-bdba-94a6bdfa0eac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-439']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-439</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6d41a046-48f6-4aef-89fc-e8025563d399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-439</value>
      <webElementGuid>62e79cac-3c83-4f1c-8eb8-9312c47d8a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Description</value>
      <webElementGuid>8eca174c-4cb9-40b8-bd4c-59cd986a6f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4765ea7d-95f7-4616-8dfc-8ddbe194bb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-439&quot;)</value>
      <webElementGuid>91f67a1e-8618-4757-b688-464a09ce0495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-439']</value>
      <webElementGuid>e0464913-43a5-4590-a309-17d43eacfbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[4]/div/div/table/tbody/tr/td[2]/div/div/div/div/textarea</value>
      <webElementGuid>863ba29a-c4a4-4e19-aabf-71c588e85d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/textarea</value>
      <webElementGuid>ccb27ef2-94c6-4002-a36b-df215f28fd66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-439' and @placeholder = 'Enter Description']</value>
      <webElementGuid>f36d1cd5-7ed9-43ad-b058-8ac13aea5d8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
