<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email tidak valid_input-178</name>
   <tag></tag>
   <elementGuidId>0a73d2b1-aeb7-4dc4-bb16-294e0298ed89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-178</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-178']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13ef7e64-26ad-408f-9588-0e9865cbf4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-178</value>
      <webElementGuid>b4d00205-8a7a-4af2-a408-c9a6865071fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan password</value>
      <webElementGuid>5e36da25-a6df-45b7-b31b-046b25862b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>812202fa-72d9-46ff-bec3-1ce196f462e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-178&quot;)</value>
      <webElementGuid>3d7f69d1-3be3-4a48-a091-1f3ae8979e40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-178']</value>
      <webElementGuid>1149b7f3-9839-4550-bcd9-b9616003a373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[4]/div/div/div/input</value>
      <webElementGuid>e32615c5-f9c0-4e72-9f2d-b0e2b7599164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>2e075e87-62ac-4907-834f-446749ee9f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-178' and @placeholder = 'Masukkan password' and @type = 'password']</value>
      <webElementGuid>6fa351fb-318f-4198-8623-674a2bffd417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
