<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email tidak valid_input-173</name>
   <tag></tag>
   <elementGuidId>5f3f2e51-b758-4001-bfff-8eff855e1462</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-173</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-173']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c3dd2d3-7540-47dc-831d-6c55de8a5a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-173</value>
      <webElementGuid>3a9030cf-cc23-423f-bb21-78ccde0da0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan password</value>
      <webElementGuid>a84614b0-40c4-4882-984c-2ab69156ece4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4f83e28a-97c7-4ad9-a90e-efcae5418739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-173&quot;)</value>
      <webElementGuid>78b9efdf-4433-4a1e-a197-a5137cc14371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-173']</value>
      <webElementGuid>5cb0b75b-1679-4f02-8a2b-108be4756510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[3]/div/div/div/input</value>
      <webElementGuid>fc0a8f68-24cf-4f8e-8bcc-f2b80a5a5ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>fdc8c71e-3755-4d09-895b-c68b14d51281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-173' and @placeholder = 'Masukkan password' and @type = 'password']</value>
      <webElementGuid>9c3d9d9e-bcee-4ca6-8a50-9ff40dc49465</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
