<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Syarat  Ketentuan, Kebijakan Privasi _4f0e13</name>
   <tag></tag>
   <elementGuidId>9652a709-a931-4eff-af48-8b1021afee64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-165</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-165']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd736df5-e0f0-447c-8384-71c36a9dd837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-165</value>
      <webElementGuid>fc6098ad-fa8d-4bf6-8a19-ab4d6f982293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama</value>
      <webElementGuid>3b2df8f3-9c1e-42b0-9d0d-61ad641e8930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b063982-9e27-49c4-9fa2-47912d6613c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-165&quot;)</value>
      <webElementGuid>d9652105-fb4a-4305-a1bc-9e4d1692538c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-165']</value>
      <webElementGuid>fccfbe50-512b-4131-ba84-c3de492ec780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>b8870c6d-7e0e-472b-b2a1-a42237535eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>93a8f57b-b4e8-4a50-800f-62c00126dae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-165' and @placeholder = 'Masukkan nama' and @type = 'text']</value>
      <webElementGuid>887e319c-c86e-4498-9f13-6cd1ea51a7e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
