<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KIARACONDONG</name>
   <tag></tag>
   <elementGuidId>e7cca910-eea0-4013-80ed-a49659657375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list-item-413-0 > div.v-list-item__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-413-0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f562f230-66ff-4f26-a853-2cf11b005e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__content</value>
      <webElementGuid>39b3ac33-1a28-4606-a6fe-e15d268b0e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KIARACONDONG</value>
      <webElementGuid>d87bf10a-2cdb-4993-bff9-3863fd148b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-413-0&quot;)/div[@class=&quot;v-list-item__content&quot;]</value>
      <webElementGuid>15142cb2-bcea-4a2b-b5e3-e754706076b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-413-0']/div</value>
      <webElementGuid>acf31383-1d53-4aa3-a968-f9cb76bfe2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA SUKABUMI'])[1]/following::div[4]</value>
      <webElementGuid>14c0a104-8fb8-4532-8c3b-1dc05b0da7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA BOGOR'])[1]/following::div[7]</value>
      <webElementGuid>8616bd35-403f-4916-9cfd-b04eb08c12cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'list-item-413-0', '&quot;', ')/div[@class=', '&quot;', 'v-list-item__content', '&quot;', ']')])[1]/preceding::div[2]</value>
      <webElementGuid>8215557f-67e8-4ab2-bd25-4d0750569d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div</value>
      <webElementGuid>f94d853e-cf78-40c1-9bf2-55d9a18824a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'KIARACONDONG' or . = 'KIARACONDONG')]</value>
      <webElementGuid>6d3a6067-3fe8-42ff-babd-bdbeb2c913d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
