<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_KEBON KANGKUNG</name>
   <tag></tag>
   <elementGuidId>5e926f95-0bd5-4b9d-8055-692e5b318ce2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-611-0']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list-item-611-0 > div.v-list-item__content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b83b230c-9208-4789-9e40-e892bfe02ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__content</value>
      <webElementGuid>3f0bcd0d-fc83-4245-aa8a-3f510f027893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KEBON KANGKUNG</value>
      <webElementGuid>76366e86-ca73-4aa3-8af3-6c334d4493bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-611-0&quot;)/div[@class=&quot;v-list-item__content&quot;]</value>
      <webElementGuid>60f5a942-8d02-46de-8442-0faffef40d9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-611-0']/div</value>
      <webElementGuid>e06d4fd7-c442-4f36-b981-148f30793017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BATUNUNGGAL'])[1]/following::div[4]</value>
      <webElementGuid>dd4f6553-dfb1-4550-8033-a1055294b739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KIARACONDONG'])[1]/following::div[7]</value>
      <webElementGuid>e1683877-6a4d-4e2e-9ffb-557e6a4f2049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'list-item-611-0', '&quot;', ')/div[@class=', '&quot;', 'v-list-item__content', '&quot;', ']')])[1]/preceding::div[2]</value>
      <webElementGuid>74851d8c-c8a8-4e00-97b7-3c8ca62cbcd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div</value>
      <webElementGuid>2fca8dac-5d6d-4440-aeaf-dce44f32c4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'KEBON KANGKUNG' or . = 'KEBON KANGKUNG')]</value>
      <webElementGuid>070d417a-2a36-4502-be83-8ae66c3ff67d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
