<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BABAKAN SARI</name>
   <tag></tag>
   <elementGuidId>f17c4e21-eb9d-4061-9423-8dc7796e8c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list-item-455-0 > div.v-list-item__content > div.v-list-item__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-455-0']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dff9dfd2-14b5-45b4-bcd0-f61e0baee563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__title</value>
      <webElementGuid>ea2d663f-e136-453a-8750-83ec09054fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BABAKAN SARI</value>
      <webElementGuid>abed3a59-c8eb-43e0-93e4-e115db137501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-455-0&quot;)/div[@class=&quot;v-list-item__content&quot;]/div[@class=&quot;v-list-item__title&quot;]</value>
      <webElementGuid>5cc1eb25-1981-4b79-b9c9-4037234a21d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-455-0']/div/div</value>
      <webElementGuid>edbf4cb7-207b-4b07-93e9-7a0eb404093e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BATUNUNGGAL'])[1]/following::div[5]</value>
      <webElementGuid>3e40cb38-913f-40a1-a0d7-4880ceab8b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KIARACONDONG'])[1]/following::div[8]</value>
      <webElementGuid>801c4caf-28ad-4708-804d-2cf0c353330a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div</value>
      <webElementGuid>203e9203-e42f-4e8a-9206-72cfeae97d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'BABAKAN SARI' or . = 'BABAKAN SARI')]</value>
      <webElementGuid>47dc0531-1615-4f2b-9a1a-6ad10285d791</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
