<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-344</name>
   <tag></tag>
   <elementGuidId>0ddc6802-52f3-4918-b4ef-80c9e42769fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-344']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-344</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de1b2fd2-6c5d-4187-a56d-a32a11f4c8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-344</value>
      <webElementGuid>fbe3e3c4-b0a7-41ed-812d-2b8764358f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Title</value>
      <webElementGuid>361c6384-ae3c-4dd3-9163-74f1008a780b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>770fa614-57bf-4d54-9945-cf60e94362fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-344&quot;)</value>
      <webElementGuid>4429a66d-5b87-4539-a891-4e32b146f33b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-344']</value>
      <webElementGuid>509dd88f-f8f7-4847-bc2a-2200d22dffc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>e468d2b2-5043-4b3d-a284-5a324efceb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f3da30a8-06e4-4a53-8a7d-4708f9bceacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-344' and @placeholder = 'Enter Title' and @type = 'text']</value>
      <webElementGuid>8ce0c3c3-73bc-4a57-81e2-7edae6b197bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
