<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-387</name>
   <tag></tag>
   <elementGuidId>717ed1bc-1f77-435f-a743-40289c9eed2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-387']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-387</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c45b025b-c804-4b73-ba71-16ec4eca4876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-387</value>
      <webElementGuid>fe466db8-1170-484a-b0d6-979eb5213a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter City / Regency</value>
      <webElementGuid>c804c018-73ce-4ee5-97cc-33b21b77a517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d496378-b93c-4edf-aad6-1d0c8924dbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3eff911a-a375-4d3a-9c3f-4d793bf94a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-387&quot;)</value>
      <webElementGuid>5ce50e69-073e-478a-a6f0-4216d5e41aa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-387']</value>
      <webElementGuid>f8875530-d9f4-4392-bf56-34b3881a5991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>dd4edb5d-f561-4dbc-af1d-f7fc07922a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>734ea442-99c6-48b7-a6d1-2cb6738b5e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-387' and @placeholder = 'Enter City / Regency' and @type = 'text']</value>
      <webElementGuid>e1cc83ce-0506-4837-b91e-81933740ee07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
