<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-259</name>
   <tag></tag>
   <elementGuidId>a5fa683e-6517-4470-8f83-89cd77ad7a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-259</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-259']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b38fb279-d416-4e93-9ebf-12196dfa77ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-259</value>
      <webElementGuid>1c92ab96-02ac-450b-a99f-ef970e182182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Villages</value>
      <webElementGuid>c971f3c3-a139-4f15-a577-634dc4b7f6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2182d90a-3c7f-4b24-9aa0-acd14e80fa69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d782ca7e-d152-4c7e-9852-044e9257b7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-259&quot;)</value>
      <webElementGuid>23eed25b-40b3-41a3-8310-e76ca520eacf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-259']</value>
      <webElementGuid>6b7aeb0a-e813-41fc-a2e2-02e87c267e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div[2]/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>7e98ce02-afe1-40d4-8c2c-ffcbd8b3edb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>ef9f4e38-df5f-4961-9a22-e2d0ea693106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-259' and @placeholder = 'Enter Villages' and @type = 'text']</value>
      <webElementGuid>cb0c1aba-a8ca-47ac-b4f0-27a1aac85660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
