<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-368</name>
   <tag></tag>
   <elementGuidId>3e210bc8-b422-4d08-b2e2-77fdefc0644c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-368']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-368</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fce05419-1768-448b-8e67-d92ca6618380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-368</value>
      <webElementGuid>b0d6cbee-1b55-4daf-a474-06bf0e6a2edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Last Name</value>
      <webElementGuid>f204a10b-2375-4c08-8c71-0abc84e86e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30d8f8d7-a56c-4ea1-9f89-420353ef5e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-368&quot;)</value>
      <webElementGuid>77afe509-32e6-473f-91b1-a6589ccd250a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-368']</value>
      <webElementGuid>58c532a3-e016-4f9c-8e5a-f1ce82b972f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>d708e8a9-bbc3-48df-b76d-b927084c64cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>dfc155bb-b86d-4b4e-9eec-9bec60262acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-368' and @placeholder = 'Enter Last Name' and @type = 'text']</value>
      <webElementGuid>1df04d19-beb4-4442-b75e-f60fad955eba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
