<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-265</name>
   <tag></tag>
   <elementGuidId>f9f7218c-db17-4bad-8414-f0f715b3ad25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-265</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-265']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cfa970c-9cb0-440a-9447-428acf2ce1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-265</value>
      <webElementGuid>fb1cccfa-203a-4a97-b2f5-92a8e3f13da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Postal / Zip Code</value>
      <webElementGuid>2e5ed709-e18b-42cb-83b2-283aa0adfb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a39d05d5-69d0-4279-a56a-d045c61a2ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-265&quot;)</value>
      <webElementGuid>d99c3673-d5bc-430e-92b5-b1b94e86b157</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-265']</value>
      <webElementGuid>40123316-c567-4514-83e4-59c240534e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div[2]/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>030476f2-20b5-4ccb-9fc9-7522b9c779e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>e097b238-2fe5-4f45-ad45-939ff53f4f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-265' and @placeholder = 'Enter Postal / Zip Code' and @type = 'text']</value>
      <webElementGuid>4c9ae608-5efa-4994-a7a3-87e930003125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
