<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__input-269</name>
   <tag></tag>
   <elementGuidId>658ba199-5cd9-46ad-9a8e-13149d977234</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-269</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-269']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9192e005-2c5d-4eea-aca0-a524166aba13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-269</value>
      <webElementGuid>1ccfd603-0b7f-43d9-89e4-95d893605cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Address</value>
      <webElementGuid>88d98780-b33d-4ffa-a3a8-69fdb254a804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>6246c1b4-6859-449f-93b5-48003f53321b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-269&quot;)</value>
      <webElementGuid>30c5a681-07b6-4a04-8ef5-f8225dfe5199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-269']</value>
      <webElementGuid>4cf31d7c-7d8a-433d-834e-0a215bb37e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div[2]/div[2]/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>4052217d-eee4-4a9a-95a8-d4b99a4c9cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>30c921d9-d559-42b2-bddc-6b82d7525c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-269' and @placeholder = 'Enter Address']</value>
      <webElementGuid>769af856-b606-4dcc-be65-56bfe928c248</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
