<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__input-409</name>
   <tag></tag>
   <elementGuidId>0d034fdd-e1ae-446c-b729-2907439a550a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-409']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-409</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fcea784e-9eb1-494c-b1ca-71aeb1aa84c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-409</value>
      <webElementGuid>56d35f69-4eed-4c69-9f0a-e9a6d7986b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Address</value>
      <webElementGuid>7d59e27b-ccd1-4494-a4f6-ab1ce590b988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a4fd769a-8619-4811-adbd-037ea7d2faf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-409&quot;)</value>
      <webElementGuid>123629d3-af78-4c77-98ae-56d0aa816080</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-409']</value>
      <webElementGuid>662ab6b9-65be-47a0-9bcf-227e97f923be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div[2]/div[2]/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>9764b73f-0ee7-453e-8054-5ad074406a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>bcf4407b-b257-4f36-b992-207ae4595fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-409' and @placeholder = 'Enter Address']</value>
      <webElementGuid>926ad391-0f43-42bc-89b4-ac9908a88c8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
