<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-442</name>
   <tag></tag>
   <elementGuidId>c19c9d0b-0e15-4932-9969-d6ef538513d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-442']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-442</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1e572d4-c019-41b7-8336-b3528f5d6b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-442</value>
      <webElementGuid>0fba84f1-8ca6-4e92-be9d-4be0013bb000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Quantity</value>
      <webElementGuid>a9458f07-44a9-46ad-81bb-3f58d29b1fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2e65c2ec-97ef-4c29-9df9-c954e5909cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-442&quot;)</value>
      <webElementGuid>9ca8749f-11ef-4f29-8099-3c2b837b1330</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-442']</value>
      <webElementGuid>24ac9a5a-4bf8-4cd0-ae39-882b0b907362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[4]/div/div/table/tbody/tr/td[3]/div/div/div/div/input</value>
      <webElementGuid>d1be7128-9ff6-471d-9bc9-2aa69b045314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/div/input</value>
      <webElementGuid>8e2e1ce1-266c-419d-82e7-872d76acb67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-442' and @placeholder = 'Enter Quantity' and @type = 'number']</value>
      <webElementGuid>57185f4e-e19b-47f6-8454-26f131d171a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
