<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lupa Password_input-163</name>
   <tag></tag>
   <elementGuidId>60a4d86d-5474-4b4a-bf8e-0354744f4bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-163</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-163']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87f67376-074f-4294-afd8-8dd561693e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-163</value>
      <webElementGuid>9d6d2880-5868-4dc9-aaf2-a6839d956567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email</value>
      <webElementGuid>93c9a08e-4efe-4702-af54-dfc282a63d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58dc673e-0259-4fd7-b759-362d50ee4f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-163&quot;)</value>
      <webElementGuid>ac3a4076-8e0a-42d8-b2f4-b64bec40f4b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-163']</value>
      <webElementGuid>2a4fb0d0-6dee-4de8-9eab-e267058d251f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>66466f28-60c4-4940-967a-a1a8684d8bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>94a7a412-feba-47ce-bcdf-7aad7588d83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-163' and @placeholder = 'Masukkan Email' and @type = 'text']</value>
      <webElementGuid>aa3a8549-8dc6-47b0-875c-bf4ac759b697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
