<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-224</name>
   <tag></tag>
   <elementGuidId>07fda68f-bd41-4352-9bcc-8155014f806b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-224</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-224']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2395eef-fd82-444c-b7ff-10753ee0d123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-224</value>
      <webElementGuid>6301eb91-6cf8-477d-9bd3-35476ef07689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter First Name</value>
      <webElementGuid>b56a62e1-869e-46af-bd7b-2a1d48043945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e00f465-5a21-4e07-9b64-50bebc863930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-224&quot;)</value>
      <webElementGuid>c062e6c6-29c7-40fb-9d3b-fbd9022d2a7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-224']</value>
      <webElementGuid>92d32fa0-5f6e-4f5a-90cc-970dcc33e5c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>4633dc58-15d6-4e08-81a4-3b0d3d829e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>6c61b13e-f8a7-47e5-83b8-a9f950062c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-224' and @placeholder = 'Enter First Name' and @type = 'text']</value>
      <webElementGuid>29cae700-161b-4aae-b807-557dcc648eae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
