<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-236</name>
   <tag></tag>
   <elementGuidId>36136bc8-1696-4e1f-abcc-43ef5b322e00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-236</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-236']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59d8c138-b32f-40ba-9b0a-df487faa5e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-236</value>
      <webElementGuid>f0c31803-819a-4b88-9a28-3f7b7e18035a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Phone</value>
      <webElementGuid>20488d6c-e594-48f4-aec6-ddd8f8227b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bfc6ed6f-0b4f-4de0-a30e-1ed2b86cfef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-236&quot;)</value>
      <webElementGuid>3e5dbea3-d644-45eb-a19f-71af089eb2b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-236']</value>
      <webElementGuid>fe0bae9f-2bec-4c27-bb20-0ed16e97adf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>bb6fbdca-095e-4821-8832-5026a7cfa214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>2589cd4d-c97e-4999-b7a2-9185c216451d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-236' and @placeholder = 'Enter Phone' and @type = 'text']</value>
      <webElementGuid>7f76d913-85d3-4801-a39b-4146bf1c013c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
