<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lupa Password_input-163</name>
   <tag></tag>
   <elementGuidId>6626fdc5-1372-44f6-a364-d034545bbe0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-163</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-163']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>114d2e5b-6675-44b9-95ed-24aceb78b078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-163</value>
      <webElementGuid>ae398b96-d95a-42b9-9f3c-5a145e40a235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email</value>
      <webElementGuid>b1aa949b-482e-4b55-9553-8b2e55ec8985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01147fb8-5196-48fe-8281-fb65aa642dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-163&quot;)</value>
      <webElementGuid>d274793e-7693-4aaa-b950-f906a966f6f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-163']</value>
      <webElementGuid>7e924444-e7ce-4e74-871d-4f47baa40ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>a176304a-a236-4dd8-912d-efc75e4f76d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>19eb7c04-8a14-4741-bf3a-b8d194641404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-163' and @placeholder = 'Masukkan Email' and @type = 'text']</value>
      <webElementGuid>05aa1dd9-0af1-43a1-a1a0-8446b66d0cc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
