<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Daftar</name>
   <tag></tag>
   <elementGuidId>823a0176-6f91-4d26-bdc2-77b08e52b090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.white--text.v-btn.v-btn--is-elevated.v-btn--has-bg.theme--light.v-size--default.primary600</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8fdf3e74-4ade-40f7-91f0-250e162f9ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>302c62f4-4696-4d12-8796-1210bc95b0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white--text v-btn v-btn--is-elevated v-btn--has-bg theme--light v-size--default primary600</value>
      <webElementGuid>3a0fa2df-7bca-45a2-8085-393880b8f7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>0eb4c038-e4b4-463b-8707-6edc7a43e1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-dialog__content v-dialog__content--active&quot;]/div[@class=&quot;v-dialog mobile-nav-dialog ma-0 v-dialog--active&quot;]/div[@class=&quot;pa-3 v-card v-sheet theme--light primary&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;d-flex justify-space-between mt-5&quot;]/div[@class=&quot;pe-0 col&quot;]/button[@class=&quot;white--text v-btn v-btn--is-elevated v-btn--has-bg theme--light v-size--default primary600&quot;]</value>
      <webElementGuid>ef1c6fb9-8390-45a5-9695-44cdeee5182c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[13]</value>
      <webElementGuid>5370eca1-3ae8-4cf9-9167-81bfdc7f76d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div[2]/div/div[2]/div[2]/button</value>
      <webElementGuid>03286ea1-92b7-4093-a9bf-fac3c67944e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/following::button[1]</value>
      <webElementGuid>31aaee99-3895-4c57-bfbd-a84f1c2d013c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaya'])[2]/following::button[2]</value>
      <webElementGuid>96e85957-c292-44e8-b31e-3f77f438a6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>e599def8-566c-41e7-94c5-08afa60d31fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>d9127c95-55bc-4da1-bb41-a6d1b098c0cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
