<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama tidak boleh kosong_input-173</name>
   <tag></tag>
   <elementGuidId>f74b7566-33e9-44da-8e0e-2110b3313d56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-173</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-173']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7be2016-2334-49e5-993b-2137584390b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-173</value>
      <webElementGuid>b0af375b-f31c-4d7c-a091-3f75cbc04c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan password</value>
      <webElementGuid>552f1965-9cb5-4438-be93-cce511874f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c6b366b0-aab8-4887-899d-a791bb7c0125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-173&quot;)</value>
      <webElementGuid>bc4ff5d3-97ad-4f51-91f9-769f3638f0ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-173']</value>
      <webElementGuid>ce263e40-eb41-4954-a75e-3397120dc664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[3]/div/div/div/input</value>
      <webElementGuid>7fc550e1-b2be-47ae-977e-f9d0cf1ef0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>71c2c31e-56b5-48fc-9a9d-9ffb0aa52b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-173' and @placeholder = 'Masukkan password' and @type = 'password']</value>
      <webElementGuid>a97e6182-8dc9-4066-943c-272eb9cb6455</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
