<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama tidak boleh kosong_input-169</name>
   <tag></tag>
   <elementGuidId>dd15ce7f-ab53-4e8d-93e7-6cfe02be7be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-169</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-169']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aff59bb3-3c7e-439a-93f6-4535154b0348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-169</value>
      <webElementGuid>d10c6d62-312c-4b6b-957a-a16482b3f92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan email</value>
      <webElementGuid>1c586ff4-9318-4288-89a1-7c49e022e50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c66fefd-e511-4103-a60a-fd60842d8639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-169&quot;)</value>
      <webElementGuid>3767d04f-af51-4d0d-aa14-eff6bcf665f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-169']</value>
      <webElementGuid>d451eb75-4c3f-4cd3-bb26-b6bd09d866d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>9cf8b8c4-602c-47c9-9fb6-f953d99df316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>885dd4bd-6532-4de7-885e-3a59856e5892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-169' and @placeholder = 'Masukkan email' and @type = 'text']</value>
      <webElementGuid>2b5a9383-4163-4bda-8bd3-9002516e8fa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
