<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-332</name>
   <tag></tag>
   <elementGuidId>ee65feab-81d4-4df1-ab26-d1c226ff6723</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-332']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-332</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3573a56c-8d02-4beb-aaf9-bd69d9b53e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-332</value>
      <webElementGuid>65895dd5-cd68-4d3d-a5e9-291ae7d81147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Title</value>
      <webElementGuid>33751009-c830-4033-b928-d7bc8a2d2b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f814ff7f-b62b-492c-ade5-9ef67a623f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-332&quot;)</value>
      <webElementGuid>0117b4a3-99bc-4ca2-a424-6631955ccee4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-332']</value>
      <webElementGuid>161a9ef6-ec3c-471b-be85-816f353e484e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>ab0ef24d-e150-4a0d-b5ef-381afa030837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>aa5c7d4e-92e3-4f4e-81d5-6ffabbce5c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-332' and @placeholder = 'Enter Title' and @type = 'text']</value>
      <webElementGuid>d899330f-bf95-49b0-96b6-17464f1ff3c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
