<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_LENGKONG</name>
   <tag></tag>
   <elementGuidId>7e770ff3-6d62-420e-a9d4-395618733c42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-545-0']/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.v-list-item__mask</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d3662ec7-c46c-477a-bdbf-e9f5f3db145f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__mask</value>
      <webElementGuid>48289a40-ece8-49a7-bf26-92f852abffbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LENGKONG</value>
      <webElementGuid>7c3748fc-80a6-4b2e-a2d6-fd57e7b84cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-545-0&quot;)/div[@class=&quot;v-list-item__content&quot;]/div[@class=&quot;v-list-item__title&quot;]/span[@class=&quot;v-list-item__mask&quot;]</value>
      <webElementGuid>1bcafae6-e11c-4807-adc4-83a694fab6a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-545-0']/div/div/span</value>
      <webElementGuid>9388f93d-32ee-46d0-9db7-dd8dcb0b4ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA SUKABUMI'])[1]/following::span[1]</value>
      <webElementGuid>dc02f07c-6cdf-4743-85d5-3f413f456b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA BOGOR'])[1]/following::span[1]</value>
      <webElementGuid>a9f264b6-f706-4b3a-87fb-c7ce4ea6a209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LENGKONG']/parent::*</value>
      <webElementGuid>d83bb5e0-b355-4eb9-b72b-f98506b452ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/span</value>
      <webElementGuid>a0e1ba2a-7a02-41a2-97bf-01f8285bf735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'LENGKONG' or . = 'LENGKONG')]</value>
      <webElementGuid>b71bb7f1-e014-4d34-afd1-3be3636ab868</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
