<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password tidak boleh kosong_input-167</name>
   <tag></tag>
   <elementGuidId>988dc65e-7683-4529-a686-5bacb7dffb67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-167</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-167']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea9b2ac4-dae1-4a29-b3fc-adbb0c7c8c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-167</value>
      <webElementGuid>b7af5a6c-ac64-454a-9f65-fe5e5157dd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Password</value>
      <webElementGuid>e6565de1-70e0-477f-ad93-a66d994fe6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cf907296-2101-41c2-bd93-ceb134aa4a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-167&quot;)</value>
      <webElementGuid>eed7981d-818f-4c7d-acda-a6a3d1ba945f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-167']</value>
      <webElementGuid>32e71198-54d1-4ebc-a90a-3007e224da12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[2]/div/div/div[2]/input</value>
      <webElementGuid>11256d1f-3e54-4fc6-b2aa-cbb95fbfebad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>9d05e705-578e-4c22-ae48-3ca996c18013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-167' and @placeholder = 'Masukkan Password' and @type = 'password']</value>
      <webElementGuid>f6f2e8f5-fe39-4dbf-a759-bd94c4803d74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
