<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lupa Password_input-471</name>
   <tag></tag>
   <elementGuidId>9f4718ea-1830-45dc-b5d1-8f4988c6211f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-471</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-471']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4a1c15a-b40c-49f0-929b-1d8e1ad2e2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-471</value>
      <webElementGuid>b5300de4-dd9c-4539-8336-db915b5ac87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email</value>
      <webElementGuid>227959c8-c708-4ac3-bd58-dcb8ef4a0352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21fee3dc-e90e-458a-be58-aab7a1fed9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-471&quot;)</value>
      <webElementGuid>d1ddc318-29e0-41e0-ba2e-11c8109d9502</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-471']</value>
      <webElementGuid>093b0d7b-8e83-4f2c-aec7-79aad8c86721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>552315e9-781d-4548-89d0-859003f2fe01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f7fe3796-a6f5-4e4b-b1e3-d72c59011a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-471' and @placeholder = 'Masukkan Email' and @type = 'text']</value>
      <webElementGuid>4383dda6-1a0c-4c49-98e7-59e76f85283e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
