<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password tidak boleh kosong_input-475</name>
   <tag></tag>
   <elementGuidId>bfb86fd3-ed10-45ed-ae4c-918a1a4eac2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-475</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-475']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0974645-f029-4466-a60f-0cf121f4377d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-475</value>
      <webElementGuid>43c0c60d-a941-4d7c-a8a9-8d5c8123f423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Password</value>
      <webElementGuid>d8bf7917-23b1-44ff-a1c1-a6527bd24e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cac844bc-e96f-4071-b3a7-dd265cc4bfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-475&quot;)</value>
      <webElementGuid>b5ab84fb-0ae3-4c5d-81b6-007317188ace</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-475']</value>
      <webElementGuid>63596d3a-1020-4a1f-8c9d-41a31cbd421e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[2]/div/div/div[2]/input</value>
      <webElementGuid>a3c5a3a9-d35a-4e3d-8eb2-7de0cfaec3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>2dd12a13-1f02-49fd-9a39-f1149017943e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-475' and @placeholder = 'Masukkan Password' and @type = 'password']</value>
      <webElementGuid>f26a55b2-5e99-4096-b469-e02e73a6d81f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
