<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Daftar</name>
   <tag></tag>
   <elementGuidId>5519ee6b-1431-4825-9095-6106203423be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.white--text.v-btn.v-btn--is-elevated.v-btn--has-bg.theme--light.v-size--default.primary600</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56ddfe22-c64b-40d7-a933-f5c074a7ac46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1eed7004-7c41-46a5-b181-0c5af3343d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white--text v-btn v-btn--is-elevated v-btn--has-bg theme--light v-size--default primary600</value>
      <webElementGuid>b8bab83f-929d-4e15-9d19-2b052da0bfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>7fb6e081-8cb7-4e59-8c79-e0d7264109a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-dialog__content v-dialog__content--active&quot;]/div[@class=&quot;v-dialog mobile-nav-dialog ma-0 v-dialog--active&quot;]/div[@class=&quot;pa-3 v-card v-sheet theme--light primary&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;d-flex justify-space-between mt-5&quot;]/div[@class=&quot;pe-0 col&quot;]/button[@class=&quot;white--text v-btn v-btn--is-elevated v-btn--has-bg theme--light v-size--default primary600&quot;]</value>
      <webElementGuid>611f9ea0-eb60-4e9f-8f08-b9b4da9e5381</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[13]</value>
      <webElementGuid>14ad59f7-b741-443a-b366-bc2e5606a2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div/div[2]/div/div[2]/div[2]/button</value>
      <webElementGuid>3f8ed2ef-84c0-4461-8b94-a9192b96d72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/following::button[1]</value>
      <webElementGuid>95aed60a-3883-4eb3-b94d-5bda3b822fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaya'])[2]/following::button[2]</value>
      <webElementGuid>ec586ade-2629-4bd7-88f5-8845d357158d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>a8d4e6b7-696c-4708-b628-ca3944568e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>4504ce99-a8a1-4d18-a8d8-6c47d5973835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
