<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Syarat  Ketentuan, Kebijakan Privasi _4f0e13</name>
   <tag></tag>
   <elementGuidId>a899bf58-e572-4573-bb7c-7fb16d3fb925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-165</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-165']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f6739b5-25aa-4392-bb91-d5f60f69d0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-165</value>
      <webElementGuid>4faf2a6f-5868-4cf2-a492-27bf084ff986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama</value>
      <webElementGuid>410e907c-5e39-4d7e-8454-6771bf23695a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5658f616-df79-47b5-98ce-ce6ce9223ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-165&quot;)</value>
      <webElementGuid>5f496f92-2280-4ea5-a46f-166cfb33b9ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-165']</value>
      <webElementGuid>e895afd3-7b04-4ccc-9679-d1b44aa18e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>24f53a8a-eadb-44fb-8af3-b807fef9e1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0327b314-13eb-4d32-8cd5-db8f5c7b357d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-165' and @placeholder = 'Masukkan nama' and @type = 'text']</value>
      <webElementGuid>6c4f9e87-1fef-43e8-8046-3d143a463264</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
