<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email tidak boleh kosong_input-173</name>
   <tag></tag>
   <elementGuidId>e1dd5bf2-5be0-4a72-ac22-d11cb2e4df51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-173</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-173']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>397d7e6d-ec0c-49c8-9d62-7889be1c5e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-173</value>
      <webElementGuid>5a3db885-e317-4564-a502-626a4f95f816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan password</value>
      <webElementGuid>00ca2b1a-46ee-4feb-b506-9378554f853d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e5844d84-2f3e-45b2-8538-f3d8d4118468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-173&quot;)</value>
      <webElementGuid>4c80cff9-3f23-4984-9166-7f37b63aff69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-173']</value>
      <webElementGuid>fb8f11e5-e865-40b4-a4a6-b33e50ef7e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[3]/div/div/div/input</value>
      <webElementGuid>2170140b-dfbe-4267-bec2-6373196558fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>714433ce-d048-4500-89c3-de93626ce085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-173' and @placeholder = 'Masukkan password' and @type = 'password']</value>
      <webElementGuid>2ac793a0-76ac-4c12-a846-69734155a0ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
