<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lupa Password_input-163</name>
   <tag></tag>
   <elementGuidId>ada367c9-fa81-4a6b-a890-3dc4fae30473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-163</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-163']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1777716-6a72-4e39-9dac-d77efa00b3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-163</value>
      <webElementGuid>454b2f07-5af2-4780-b8ab-089c357ec91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email</value>
      <webElementGuid>da35790f-9227-4304-abab-2dca3d31b410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>512de0fc-280f-46a0-ac5a-96619ba31b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-163&quot;)</value>
      <webElementGuid>23033bf1-2abd-4cc0-a67a-30dcd48a3214</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-163']</value>
      <webElementGuid>76c3d994-9c88-4426-9837-4e59dc760ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>986985ef-d44c-4bf8-896c-c37b25d8217e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>13e07dd1-ba3c-49e1-8a32-20c491e24416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-163' and @placeholder = 'Masukkan Email' and @type = 'text']</value>
      <webElementGuid>aaffa248-bd9f-4dda-a791-2d99dfa236a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
