<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-224</name>
   <tag></tag>
   <elementGuidId>2eb9f18a-1201-4e09-92d4-520d2b243635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-224</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-224']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9165896-6c17-4dc6-9fcb-89a43a5914d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-224</value>
      <webElementGuid>acc916cf-a6b7-434a-b25c-c7024e5b01a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter First Name</value>
      <webElementGuid>d38ae131-be26-46c6-86c0-fa8297833fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c00fb83-6f5e-4c8e-9705-a0b26c8f6826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-224&quot;)</value>
      <webElementGuid>85ec3dfb-a1e5-490e-a94a-efe615358cff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-224']</value>
      <webElementGuid>528afb3c-55fa-4f1a-b653-cb2157507ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>6ab740e9-b044-4c00-af13-77cc7eb1d9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>f3d2775b-c41e-4539-8215-3dd6176d7b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-224' and @placeholder = 'Enter First Name' and @type = 'text']</value>
      <webElementGuid>842a6325-e282-4bbf-9cd4-82cdddd10291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
