<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-232</name>
   <tag></tag>
   <elementGuidId>da891663-a150-4510-8f39-c4d77af2481e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-232</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-232']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbb154c7-84a0-46c6-94cb-094a36be1bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-232</value>
      <webElementGuid>8d6b5898-726c-405c-aace-2b421e824661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Email</value>
      <webElementGuid>a10564ed-ec82-4c98-91d4-7fc3714850f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48ce6687-67e5-4d70-b17c-d29c9180d96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-232&quot;)</value>
      <webElementGuid>1004bf30-070f-4d0c-8bff-d479a77f2058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-232']</value>
      <webElementGuid>e8bc995d-9c51-403e-9a96-c5f37bc60c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>d3394f50-bec2-48b8-9143-5e7f2d198f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>68eb20b6-c507-41b9-9291-8136a5fff60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-232' and @placeholder = 'Enter Email' and @type = 'text']</value>
      <webElementGuid>3f899c57-748e-4f1d-a90c-0bcfcd0457ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
