<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-236</name>
   <tag></tag>
   <elementGuidId>bce795b8-95c2-4455-a30e-6473cb20fcbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-236</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-236']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cf807cc-f786-46e9-aaea-06c14370d36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-236</value>
      <webElementGuid>2fe25027-197d-4dc9-a86d-70e23149968c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Phone</value>
      <webElementGuid>f8309174-7df5-4a90-948a-c22b65908b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b214356-7a35-490c-b850-ab91d609541c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-236&quot;)</value>
      <webElementGuid>4b51120c-c212-4819-8c16-a9f09dc61dab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-236']</value>
      <webElementGuid>283e8ad8-943d-4efa-8793-c6efc5cc4000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>14d452f5-5b44-4fcd-bfe3-e88425ce239f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>e1aa9a16-433c-4bea-865e-7f02e5cedb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-236' and @placeholder = 'Enter Phone' and @type = 'text']</value>
      <webElementGuid>d72e62e1-fab9-4b95-9d9b-4d87c415ad74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
