<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lupa Password_input-163</name>
   <tag></tag>
   <elementGuidId>0979435a-e6f4-45cd-9446-6895f22e8400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-163</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-163']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>910cc620-79c6-4268-b848-2ba3e2f4047f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-163</value>
      <webElementGuid>0c9c4457-cbc5-4e41-9733-c7fe560d2371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email</value>
      <webElementGuid>6648326e-5087-461d-b3f2-41f6f2a4a545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30e2c84e-e133-464f-aef7-6a04cfe98d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-163&quot;)</value>
      <webElementGuid>deaa7728-ff0f-4ddd-ab8c-50447a3fd48f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-163']</value>
      <webElementGuid>4934f5c3-577a-4af2-b202-592df9470dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>81d9c3b9-7da3-4033-a089-9a6eb2dc5b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>174abdff-ec80-4dd9-8997-b8da7f4752e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-163' and @placeholder = 'Masukkan Email' and @type = 'text']</value>
      <webElementGuid>b41ec837-b715-45cd-b059-c7029977f463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
