<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__input-439</name>
   <tag></tag>
   <elementGuidId>2b60ab30-b960-4062-8783-44b4f029f7f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-439']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-439</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2a80f873-02d3-44db-be27-8ae3c1d9dc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-439</value>
      <webElementGuid>2d52d7cd-f181-4141-b5bd-8a8852f6cb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Description</value>
      <webElementGuid>a5f5e004-e07c-46ef-9055-4e08a5fe1e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>833ffa92-5910-4879-b8a5-f8acb46c0b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-439&quot;)</value>
      <webElementGuid>3fea2b7a-b9bb-4527-92fa-d0188b9a1a5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-439']</value>
      <webElementGuid>37bb6e5c-814c-468d-a903-c10fb3c49208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[4]/div/div/table/tbody/tr/td[2]/div/div/div/div/textarea</value>
      <webElementGuid>5887d6d1-ab57-403f-95d2-f19f004b05b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/textarea</value>
      <webElementGuid>d6c3bf50-7698-4230-aaf3-c3f5450ff71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-439' and @placeholder = 'Enter Description']</value>
      <webElementGuid>4b902015-27fb-40d9-a6d1-9fe62280ae48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
