<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email tidak boleh kosong_input-321</name>
   <tag></tag>
   <elementGuidId>8ce97ecf-bc60-4a35-ac0b-4cacedc19c91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-321</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-321']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdd1259f-dd10-4fc6-ad3b-42dde91ef8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-321</value>
      <webElementGuid>cf6a1b3e-db87-41e2-b26d-c07c2ed8b059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Password</value>
      <webElementGuid>434bb88f-42d4-4286-9302-d9928a409319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7ac7d889-6864-474a-97f7-9c552970fd0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-321&quot;)</value>
      <webElementGuid>a3f347e9-2fbb-43da-b45f-794b0b89fe82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-321']</value>
      <webElementGuid>4ae29d90-9171-47d0-a780-5057f9200769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[2]/div/div/div[2]/input</value>
      <webElementGuid>3698f00f-91c3-4889-abd7-b2898aec0699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>9298549d-2c6f-4762-95f8-5ec63a023318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-321' and @placeholder = 'Masukkan Password' and @type = 'password']</value>
      <webElementGuid>f1bcb86b-c3dc-4a36-8121-4f6ae56c2fb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
