<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lupa Password_input-317</name>
   <tag></tag>
   <elementGuidId>da63bac9-844e-40d3-9bce-a1851a1facad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-317</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-317']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31b503c2-6baa-45f5-9cbc-acbe8462e467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-317</value>
      <webElementGuid>882f61c8-9dc9-4588-9d4f-eaf7fde1087e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Email</value>
      <webElementGuid>6dd35f74-9b08-4b57-b17e-0ecfb62fd0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c161841-02cc-46b4-9182-11ab472d6250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-317&quot;)</value>
      <webElementGuid>7c9a6181-5583-45ef-9544-e5c1a566b258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-317']</value>
      <webElementGuid>ad5d5f91-9188-467c-a809-0f2aefddd1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>68a68513-b249-4e6a-88b9-1701cea06683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>30fa15fd-0944-4753-9e23-7d3cdafffba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-317' and @placeholder = 'Masukkan Email' and @type = 'text']</value>
      <webElementGuid>61d588d8-1ca1-4bf7-b963-822b5d5ec3bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
