<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password tidak boleh kosong_input-167</name>
   <tag></tag>
   <elementGuidId>3f952eeb-28bc-4f54-9ae7-d6f0bcc7dcbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-167</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-167']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa38906f-6f33-4438-b9f5-4b90ae478ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-167</value>
      <webElementGuid>9b0ecbe8-e4f6-4198-b5d7-4afb6586f452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Password</value>
      <webElementGuid>4183a665-7168-44a0-ab9f-7091dbf262be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c20c27ce-6344-4f77-8969-89b0a32d8a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-167&quot;)</value>
      <webElementGuid>727992d2-c9b2-4728-80b8-b06d81969457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-167']</value>
      <webElementGuid>7608a447-178f-4c91-b152-7a434263acc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[2]/div/div/div[2]/input</value>
      <webElementGuid>13d29cb2-b7ab-46a4-a618-9a92172f9dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>62e68aa2-9c98-4281-8ef1-8697345b127c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-167' and @placeholder = 'Masukkan Password' and @type = 'password']</value>
      <webElementGuid>a5d97c9d-266e-4dcc-952b-727a07a85b18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
