<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-286</name>
   <tag></tag>
   <elementGuidId>32ffc884-90f9-4e6b-b77e-7451f15f326f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-286</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-286']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f991b44-5102-4868-be89-2fc46d4ebb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-286</value>
      <webElementGuid>d5a52a59-2210-4df7-ae1e-ab4f47fc92a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Invoice</value>
      <webElementGuid>f2f79719-90b5-4d54-99fb-010640522ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b18bd7af-3ff8-4632-a33c-e60442ee0b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-286&quot;)</value>
      <webElementGuid>d5d754e5-e73e-4af9-9b3c-32d7785b152f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-286']</value>
      <webElementGuid>b0a488a6-0f82-44ad-bff4-381f63aa74a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>65069762-8f5f-41f4-a571-3019d9762de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>704fc6cb-4472-4eeb-a626-7c8e2ea26b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-286' and @placeholder = 'Search Invoice' and @type = 'text']</value>
      <webElementGuid>ce04e5ed-ea7a-474e-bdd9-a638c022187f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
