<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Syarat  Ketentuan, Kebijakan Privasi _d9a892</name>
   <tag></tag>
   <elementGuidId>cdd7bd6f-dbab-4816-9295-66f295a8b0e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-169</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-169']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cc87351-d199-4d21-80fe-218154884e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-169</value>
      <webElementGuid>ecca749b-852e-4763-bb21-7604c11977f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan email</value>
      <webElementGuid>de985bcc-be7c-411f-aa5e-d0d2d90764a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3fadb68-bc8b-4515-99f1-26176aa2ed42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-169&quot;)</value>
      <webElementGuid>a962111f-9737-45eb-a51b-01d97a951b08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-169']</value>
      <webElementGuid>fabae2ef-8ce8-4e50-b1bc-4b0212d5c1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>33ec5940-b8b1-48d4-9932-156ce0fe4852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>075d8095-c1e3-43fc-b89d-28b626577aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-169' and @placeholder = 'Masukkan email' and @type = 'text']</value>
      <webElementGuid>c56ba0a0-a54d-4ee7-85dc-95f2d2c123e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
