<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Syarat  Ketentuan, Kebijakan Privasi _4f0e13</name>
   <tag></tag>
   <elementGuidId>48744016-2042-4f0b-a348-70737d7f6867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-165</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-165']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8dd5a9cf-7354-44be-b26f-5406aff17a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-165</value>
      <webElementGuid>7578ec1b-c5a4-449a-ae63-c97c55fbe162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama</value>
      <webElementGuid>7d69a4fb-a51d-4b83-9bf7-76b49aa61e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ed3b3ee-fe14-41f9-825a-965666d1c546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-165&quot;)</value>
      <webElementGuid>c4f7d253-ef7a-414b-9a77-957fa4517a38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-165']</value>
      <webElementGuid>69404fb2-c154-47fa-846c-17eacb385f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>3eb42ff4-6394-40e0-a9e9-f797a5e62ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4abca5dd-02ca-47c4-909e-f92fff0f2764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-165' and @placeholder = 'Masukkan nama' and @type = 'text']</value>
      <webElementGuid>19af15d9-8c2c-4e4d-a68d-81d1f0aea244</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
