<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-381</name>
   <tag></tag>
   <elementGuidId>c684f2aa-3596-4d0a-b9c8-26b851b3b687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>kiarakak</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-381</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37d64019-cf50-4892-a864-5c6f9b64fac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-381</value>
      <webElementGuid>03f9f9d0-ef5c-436a-86f8-ca86a8a9e15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Districts</value>
      <webElementGuid>7091c31f-3496-4c0f-82cf-803940dfc492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e620d296-9900-4c80-846c-f73a09af1552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>877b9b43-7236-470c-b1e8-8bebc6099920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-381&quot;)</value>
      <webElementGuid>b567c178-dca4-4de4-9a3c-b4fc5b0765b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-381']</value>
      <webElementGuid>01bb1204-5647-4af8-be39-fbf5cae635f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div[2]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>9786b32c-bee7-47e8-9d94-219c0d18a06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>156530e0-6ad5-42be-9d6d-6e6e008a2f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-381' and @placeholder = 'Enter Districts' and @type = 'text']</value>
      <webElementGuid>6c1c14ec-0233-4a89-bcd2-f4482dae97ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
