<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-352</name>
   <tag></tag>
   <elementGuidId>dd10fa47-c27e-4607-a232-602df20285aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-352']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-352</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24a332a1-5a3a-464d-9d1f-c5625b168d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-352</value>
      <webElementGuid>417847e8-3c68-4ae5-af2e-d15d16fa64a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter First Name</value>
      <webElementGuid>98276d21-68f0-4515-b45a-24519f21b876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f4aad47-f78a-4e82-9d1a-df3aa45d84d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-352&quot;)</value>
      <webElementGuid>19e6d7ff-d65f-45a7-916e-6c1a159b469f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-352']</value>
      <webElementGuid>279ebd79-39c3-4306-8eba-4917bf621481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/form/div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>32127c56-7113-4a09-a870-178b303704d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>fe7895c1-9320-4f9d-9142-dda21e2bc858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-352' and @placeholder = 'Enter First Name' and @type = 'text']</value>
      <webElementGuid>7e2dc504-b709-4eb5-86d0-1813cec1b1f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
